.
./flist
./flist/filelist.f
./flist/readme.md
./run_simulation.do
./Project Abstract.pdf
./sim
./sim/syn_fifo
./sim/syn_fifo/tb_Sync_FIFO.sv
./sim/ahb
./sim/ahb/master
./sim/ahb/master/run.do
./sim/ahb/master/tb_ahb_master.sv
./sim/ahb/master/AHB_master_tb.v
./sim/ahb/master/wave.do
./sim/ahb/master/testcases.png
./sim/ahb/slave
./sim/ahb/slave/run.do
./sim/ahb/slave/AHB_slave_tb.v
./sim/ahb/slave/wave.do
./sim/ahb/slave/testcases.png
./sim/apb
./sim/apb/apb_top
./sim/apb/apb_top/tb_apb.sv
./sim/apb/master
./sim/apb/master/tb_apb_master.v
./sim/apb/slave
./sim/apb/slave/tb_apb_slave.sv
./.git
./.git/config
./.git/objects
./.git/objects/pack
./.git/objects/pack/pack-537a40ad47edefe25943f6a64d2d5c19a58aa01c.idx
./.git/objects/pack/pack-34446ded0ce3640eb5fb48d3a03ef16506527849.idx
./.git/objects/pack/pack-34446ded0ce3640eb5fb48d3a03ef16506527849.pack
./.git/objects/pack/pack-34446ded0ce3640eb5fb48d3a03ef16506527849.rev
./.git/objects/pack/pack-537a40ad47edefe25943f6a64d2d5c19a58aa01c.pack
./.git/objects/pack/pack-537a40ad47edefe25943f6a64d2d5c19a58aa01c.rev
./.git/objects/info
./.git/hooks
./.git/hooks/sendemail-validate.sample
./.git/hooks/post-update.sample
./.git/hooks/pre-push.sample
./.git/hooks/update.sample
./.git/hooks/pre-receive.sample
./.git/hooks/pre-rebase.sample
./.git/hooks/push-to-checkout.sample
./.git/hooks/applypatch-msg.sample
./.git/hooks/commit-msg.sample
./.git/hooks/pre-commit.sample
./.git/hooks/prepare-commit-msg.sample
./.git/hooks/pre-applypatch.sample
./.git/hooks/fsmonitor-watchman.sample
./.git/hooks/pre-merge-commit.sample
./.git/index
./.git/lfs
./.git/lfs/tmp
./.git/packed-refs
./.git/branches
./.git/refs
./.git/refs/heads
./.git/refs/heads/main
./.git/refs/tags
./.git/refs/remotes
./.git/refs/remotes/origin
./.git/refs/remotes/origin/HEAD
./.git/HEAD
./.git/FETCH_HEAD
./.git/logs
./.git/logs/refs
./.git/logs/refs/heads
./.git/logs/refs/heads/main
./.git/logs/refs/remotes
./.git/logs/refs/remotes/origin
./.git/logs/refs/remotes/origin/HEAD
./.git/logs/HEAD
./.git/description
./.git/info
./.git/info/exclude
./src
./src/syn_fifo
./src/syn_fifo/Sync_FIFO.sv
./src/ahb
./src/ahb/master
./src/ahb/master/ahb_master.sv
./src/ahb/master/AHB_master.f
./src/ahb/master/AHB_master.sv
./src/ahb/slave
./src/ahb/slave/AHB_slave.sv
./src/ahb/slave/AHB_slave.f
./src/apb
./src/apb/apb_top
./src/apb/apb_top/apb.sv
./src/apb/master
./src/apb/master/apb_master.sv
./src/apb/slave
./src/apb/slave/apb_slave.sv
./uvm
./uvm/ahb
./uvm/ahb/readme
./uvm/apb
./uvm/apb/apb_test_pkg.sv
./uvm/apb/apb_coverage_pkg.sv
./uvm/apb/master_apb_main_sequence_pkg.sv
./uvm/apb/slave_apb_monitor_pkg.sv
./uvm/apb/slave_read_seq.sv
./uvm/apb/master_apb_monitor_pkg.sv
./uvm/apb/slave_apb_driver_pkg.sv
./uvm/apb/run_master.do
./uvm/apb/master_apb_driver_pkg.sv
./uvm/apb/master_apb_seq_item_pkg.sv
./uvm/apb/master_apb_sequencer_pkg.sv
./uvm/apb/master_arb_if.sv
./uvm/apb/run_slave.do
./uvm/apb/slave_apb_sequencer_pkg.sv
./uvm/apb/apb_config_pkg.sv
./uvm/apb/apb_master.sv
./uvm/apb/coverage_rpt.txt
./uvm/apb/wait_sequence.sv
./uvm/apb/read_mast_seq.sv
./uvm/apb/TOP.sv
./uvm/apb/slave_apb_main_sequence_pkg.sv
./uvm/apb/apb_env_pkg.sv
./uvm/apb/slave_apb_seq_item_pkg.sv
./uvm/apb/coverage_rpt_slave.txt
./uvm/apb/apb_slave.sv
./uvm/apb/apb_scoreboard_pkg.sv
./uvm/apb/master_apb_agent_pkg.sv
./uvm/apb/slave_apb_agent_pkg.sv
./README.md
